### ISSUE TITLE
[Latest SDL1 Dev] Some quickstart configs don't take affect when selected

### ISSUE THREAD

**Issue by blinkydoos** [midwan/amiberry#198]
### Expected behavior

Change the config to what's listed on screen

### Actual behavior

Changes to wrong listed config

### Steps to reproduce the behavior

Example, choose Quickstart A1200 then choose Amiga 500. The A500 preset says it should be `1.3 ROM, OCS (most common) etc.` but if you look in the Chipset section it says `ECS Agnus` is selected.

I think there should be a button in the Quickstart section to 'Set Configuration' like WinUAE has.

**Comment by midwan** [comment]
Which button in WinUAE are you referring to?
![image](https://user-images.githubusercontent.com/3877365/34781403-07ce74fa-f626-11e7-8302-b8edf61ce421.png)

The options mismatch is probably something I can fix though.

**Comment by midwan** [comment]
@blinkydoos I can't recreate the problem using the steps you mentioned exactly:

- Startup emulator, goes in Quickstart panel with A500 OCS selected -> Chipset is incorrectly at ECS
- Change Quickstart option to A1200 -> Chipset is set to AGA correctly
- Change Quickstart option to A500 OCS -> Chipset is set to OCS correctly

So from what I can see, it's only the starting configuration that is not correctly set (should had been OCS instead of ECS), but otherwise changing Quickstart modes seems to work.

Did you try something different?

**Comment by blinkydoos** [comment]
Mine has this button -
![winuae quickstart](https://user-images.githubusercontent.com/27903587/34782608-2ce095e8-f621-11e7-8aeb-35497f0aab2e.png)

Strange things are happening with the Quickstart, I can't reproduce the problem again at the moment but when I chose A1200 it had JIT turned on !? I'll mess withit a bit more.

**Comment by blinkydoos** [comment]
I think it's only the top config for A500 that doesn't take effect (most common).

Choose Quickstart -
`Amiga 500`
`Config 1.3 ROM, ECS Agnus, 1 MB Chip RAM`

Change to `A1200` then back to `A500` and it's still on the previous A500 config that was set (ECS, 1MB Chip).

But as I said, I think there are other weird things happening like JIT turning on on the A1200 config.

**Comment by midwan** [comment]
@blinkydoos 
Regarding the WinUAE screenshot, which version are you running? My screenshot is from the latest stable (v3.5.0 currently)

Regarding Quickstart:
I don't have JIT turning on here, but I did fix the default_prefs in a previous commit to set the cachemem to zero (so JIT would be turned off by default), because it wasn't there. Are you testing with the latest version?

I can recreate the steps you mentioned above: A500 ECS 1MB Chip -> A1200 -> A500 : does not set the chipset to OCS as  it should.
I think this might be the same problem as the starting up not setting the proper A500 settings, so I'll fix that and see if it solves both problems.

**Comment by blinkydoos** [comment]
I'm using WinUAE v3.6.0 beta 6.

I think the last commit I built from was https://github.com/midwan/amiberry/commit/c70d2c09e94194be09943c9cfefdad99949844cf

I found some other things but I can't reproduce, my brain is a bit scrambled now!

**Comment by midwan** [comment]
This is fixed for now, we'll see about adding a button later if needed

**Comment by blinkydoos** [comment]
I think this happens on all Quickstarts that have multiple configs, the top one doesn't take effect. You may have already fixed this but i'll say it anyway.

If you choose Quickstart A1200 and the 4MB Fast config, then choose A500, then back to A1200 (the top config should be 'Basic non-expanded') but the RAM section still says 4MB Fast.

**Comment by midwan** [comment]
@blinkydoos it should be fixed now, I tested the scenarios you described and I could see the RAM, CPU and Chipset options getting updated, even after starting emulation. :)

**Comment by blinkydoos** [comment]
You fixed nearly all the issues I reported in one fell swoop ! Impressive work ! I'll have to wait till tomorrow though to rebuild and check but I'm sure it will be fine now :)

**Comment by blinkydoos** [comment]
It still doesn't apply the settings in Quickstart with the top config. I think a 'Set Configuration' button is needed. This is probably the reason why WinUAE added it. You can reproduce by doing this again -

> I think this happens on all Quickstarts that have multiple configs, the top one doesn't take effect. You may have already fixed this but i'll say it anyway.
> 
> If you choose Quickstart A1200 and the 4MB Fast config, then choose A500, then back to A1200 (the top config should be 'Basic non-expanded') but the RAM section still says 4MB Fast.

(I'm using SDL1 built from https://github.com/midwan/amiberry/commit/ff38ef1e3e6bf6ef7d61023295704fc8bc6cc1f5)

**Comment by blinkydoos** [comment]
Another thing that i've been trying to report but Github stopped working ! When selecting Quickstarts, I think it's working fine now when selecting with the mouse but when using the keyboard/joystick it doesn't.
