### ISSUE TITLE
[Bug] Disc - unplayable

### ISSUE THREAD

**Issue by nemo93** [midwan/amiberry#355]
### Expected behavior
Be able to play the game.

### Actual behavior
Screen freezes anytime you launch a game. Despite changing Amiberry params like Fast Copper, Blitter etc.

### Steps to reproduce the behavior
[Disc_v1.1_1503.lha] + Amiberry 2.21. Launch the game as normal. Training > chose a player and next you'll see the game screen but frozen. You can see your player on the right side but stuck. This game works perfect in previous Amiberry releases.

**Comment by nemo93** [comment]
Small comment: game plays fine if you keep pressing down the "start" button (on my xbox 360 pad) all the time. Obviously not ideal but the emulation at least (sound, gfx) is fine. Perhaps a simple tweak in the settings would help here? I just couldn't find which one.

**Comment by midwan** [comment]
@nemo93 
Could you please test with the latest version from `master` and confirm if this is still an issue? If it's already fixed with that, perhaps we don't have to do anything further. :)

**Comment by nemo93** [comment]
@midwan hi. Indeed it's still there with latest master (2.24 as of typing).

**Comment by midwan** [comment]
This is fixed with 29fe7770ec61a26224fef6ad74dfe679b248ed53 in `dev`

**Comment by nemo93** [comment]
Confirm that it 100% fixed. Awesome! Thank you.

**Comment by nemo93** [comment]
Bug is back with latest 2.25 (need to hold start button down).

**Comment by midwan** [comment]
@nemo93 the `dev` branch is not merged into `master` yet, so the bug is not really "back" - it's still fixed in `dev` only for now.

The reason I haven't merged that in, is that the performance with the new custom code has gone down, and I want to see if I can optimize it first. ;)

**Comment by midwan** [comment]
this will be merged into `master` as soon as beta testing is complete. Since there's nothing else to do about this issue, I'm closing it for now.
