### ISSUE TITLE
CD emulation for A500/1200

### ISSUE THREAD

**Issue by solskogen** [midwan/amiberry#37]
The CD emulation is only(?) for CD32 pr. date. Would like to be able to mount a iso (AmigaOS 3.5 and 3.9)

**Comment by CypherXG** [comment]
Make a Directory and copy all Files in there.
Rename the Directory like the CDRoms name

**Comment by solskogen** [comment]
Yes, I know that works. But the point here is the missing cdrom support :)

**Comment by HoraceAndTheSpider** [comment]
I believe this is now fixed ... CDs working fine for CD32 and I think now also available on all machines.

**Comment by ransom1122** [comment]
As the above comment above. Was cd mount issue fixed for a1200 config in Amiberry version 2?
You can test with T-Zer0 AmigaCD made by DamienD. It has HDF & CD image combined. I cant get the cd image mounted.. once you load tzer0 HDF after you skip cracktro with left mousebutton it shows on the screen cd failed to mount & there is no ingame audio because of it.

**Comment by ransom1122** [comment]
There seems to be confusion on this topic. CD mount issues still exist for me in workbench environment? Can anyone confirm it is working?

**Comment by CypherXG** [comment]
CD32 ca mount a CDRom only in the moment. 
But the CD32 use the cd.device in the extend rom. You cannot use this cd.device with an A1200.
Also it doesn't work if you are using another kickstart as an CD32 one...
So you have to wait....

**Comment by ransom1122** [comment]
@Horace And The Spider - Is this issue on the to do list, what will ETA be for a fix any idea?
