### ISSUE TITLE
Loading config that enables JIT causes emulator to hang

### ISSUE THREAD

**Issue by amyren1966** [midwan/amiberry#621]
Using Restart from the GUI does not seem to "clean up" in the same way as Quit and relaunch amiberry does. Switching between configs and using Restart may cause black screen and system freeze after a few switches.

This can be experienced by having multiple different configurations in you setup.
(I guess the more different the setups are, the easier to reproduce the problem)
1. Start up one of your emulator configs
2. Press F12 and load another config, Restart amiberry 
3. Launch the setup you selected at step 2.
4. Repeat step 2 and 3 until you get the problem. 
5. If you cant reproduce the problem, try to Respeat step 2, then change something (increase memory or change cpu type, add a harddrive etc.) before taking step 3.

System:
Amiberry 3.1.3 on Amibian 1.5ee
Raspberry Pi 4B (4GB)

Additional notes:
This problem was much worse before, with version 3.1.1
Then even quitting amiberry did not clean up properly.
Example, I have a WB3.9 and a Aros68k setup. If I started from cold boot and launched WB3.9 first, I could never get Aros68k to run just by using Restart. Also I could hardly get Aros68k to start even if I quit amiberry to commandline and relaunched amiberry, if WB3.9 had been running just before.
To get Aros running I had to make sure autostart was not active, and power off/on, then launch Aros before any other config had been running.
With 3.1.3, Aros can be started after WB3.9, at least most of the time.

**Comment by midwan** [comment]
This should be fixed with 81da26b590a6babb3639ee616ce578658f33da2f

**Comment by DJP75** [comment]
unfortunately this isnt resolved yet,
amiberry 3.3 on dietpi and rpi4

switching from one config to another by double clicking directly in the name,give a black screen
switching from one config to another by click load and then reset may start or give a black screen
restarting the emulator and clicking any config,quits at login screen

also,if i have a config when i want to use CD,this doesn't always work
switching with the second method,if i'm lucky and boots,the CD never mount
if i autostart the config,the CD never mount unless i mount an image and save the config
(in other words,it works if you start with an image already mounted)
if i start with GUI,it always mount CDs

**Comment by midwan** [comment]
In that case, please attach some of the configs that you have trouble with, so I can try to recreate this.

**Comment by DJP75** [comment]
here they are 
[configs.zip](https://github.com/midwan/amiberry/files/5372641/configs.zip)

**Comment by midwan** [comment]
@DJP75 
Thanks, I was able to recreate the problem. Here's what I've found so far:
I created 4 different configurations:
1) A500
2) A500+
3) A1200
4) A1200 with JIT

All of them with the default options from Quickstart, to make sure there are no further complications.
When testing to load one after the other, the all work until I try to go from a non-JIT config to a JIT one. Then I got the emulator to hang, with a black screen as you described.

Then I tested just going from the A1200 to the A1200 JIT config, and I could recreate the same problem.
Comparing the two configs, the only differences are the CPU options of course. Specifically, the following:

For the non JIT config:
```
cpu_type=68ec020
cpu_compatible=true
cpu_24bit_addressing=true
cpu_cycle_exact=true
cpu_memory_cycle_exact=true
cycle_exact=true
compfpu=false
cachesize=0
```

And the same options for JIT become:
```
cpu_type=68020
cpu_compatible=false
cpu_24bit_addressing=false
cpu_cycle_exact=false
cpu_memory_cycle_exact=false
cycle_exact=false
compfpu=true
cachesize=16384
```

So something is not happy when doing that from loading config files, because it seems to work if you just do the same from the GUI.

I'll have to investigate further.

**Comment by DJP75** [comment]
this is an interesting find! maybe this jit-interference issue also affect the CD?
thanks!

**Comment by midwan** [comment]
@DJP75 
I found one more detail today:
It seems that the problem only occurred for me when I used double-click to load the next config during the tests.
If I used the Load and Reset buttons instead, I didn't get a black screen.

Can you confirm if that's the same at your end as well please?

I found a small difference in the logic between the two methods, so I'm going to do some more experiments to see if that solves it.

**Comment by midwan** [comment]
@DJP75 
Please test with the current `dev` branch version, and see if you still have the same issue(s) mentioned above?

**Comment by DJP75** [comment]
how do i do that? i have already a backup of the sd card,just in case i mess up.. :)

**Comment by midwan** [comment]
You can use `git clone` like so:
```
git clone https://github.com/midwan/amiberry -b dev amiberry-dev
```
That will clone the whole repo under your current directory, in a subdir named `amiberry-dev`.
Then you just `cd` into it, and compile it for your target platform as usual (e.g. for RPI4 using dispmanx: `make -j4 PLATFORM=rpi4` or using only SDL2: `make -j4 PLATFORM=rpi4-sdl2`).

Once it's compiled, it will generate an executable named `amiberry`, in the same directory. Just copy this over to where you have your actual config files etc. (remember to rename it while copying, so it doesn't overwrite your previous one! e.g. `cp amiberry ~/path-you-want/amiberry-dev`).

Then you can just launch `amiberry-dev` from that directory and test it out.

**Comment by DJP75** [comment]
First command give an error.the sdl2 one,flashes a lot of text but at the end no amiberry executable

![IMG_20201015_134623](https://user-images.githubusercontent.com/72798328/96120319-a0571900-0eee-11eb-976c-a2cd441f64b1.jpg)
![IMG_20201015_134445](https://user-images.githubusercontent.com/72798328/96120325-a220dc80-0eee-11eb-95b0-337978ef2c3b.jpg)

**Comment by midwan** [comment]
Make sure you have all the requirements in place, as mentioned in the Readme: https://github.com/midwan/amiberry

Since you're on Amibian, there may be a custom version of SDL2 included, better check with Gunnar on the exact process there to be sure.

**Comment by DJP75** [comment]
I use dietpi,no amibian. I will check the docs and report the results,thanks!

**Comment by DJP75** [comment]
installed all the -dev packages but no result :(

**Comment by midwan** [comment]
Make sure you have the `build-essential` package installed also, otherwise you don't have the compiler in your system. ;)

**Comment by DJP75** [comment]
Finally made it!
I can now switch from a non jit config to a jit one and viceversa!

Restarting the gui and doubleclicking,throw me to login. Selecting load then start works.

CDs arent still mounting and now i cant select the tynemouth joystick adapter in the input section

**Comment by midwan** [comment]
@DJP75 
OK, let's handle each problem separately, in different issues.
This one is fixed, so I'll close it. I can recreate the other you mention about Restart then double-click on a config -> crash, so I'll open a new one for that.

Please open a separate one for the CD mounting problem, with all the related details in it.
And one for the controller issue you mention, though I cannot see a problem with that in my end (all my controllers show up normally in the list can can be selected).
