### ISSUE TITLE
Xenon 2 not working since Version 3.1.2

### ISSUE THREAD

**Issue by Lex15** [midwan/amiberry#638]
Xenon 2 will not load since version 3.1.2. I'm using the two disk IPF version on a pi 4 rasbian desktop. Using default A500 config.

**Comment by Retro1968** [comment]
I cannot confirm that. Maybe you should reinstall amiberry. It could be a good idea to delete all folders in "/opt/retropie/configs/amiga/amiberry/ without the "conf" folders before you reinstall amiberry (source-files). After the installation you should go into the amiberry menue to "Paths" and click on "Rescan Path" and "Update WHDLoad Database/XML". The second one should be clicked regularly.

**Comment by midwan** [comment]
@Lex15 
I don't have the IPF version to test with, but I just tested the LHA 2-disk version (specifically, Xenon2_v1.12_2Disk_0297) and it seems to work fine with the latest Amiberry here.

Can you elaborate more on "will not load"? Perhaps your disks are problematic, if everything else works? Have you tried an alternative version?

**Comment by Lex15** [comment]
I've tried the disks on WinUAE and they work. So I'm pretty sure they are fine. I tried running them on different pre built versions on a fresh Rasbian desktop.  The game runs fine on 3.1.0 but on 3.1.2 and thereafter the game never loads properly the screen just stays black.

**Comment by midwan** [comment]
@Lex15 does it happen with any other IPF images?
It's a little tricky to find out what's wrong, if I can't recreate it here. :(

**Comment by Lex15** [comment]
I've found the issue, since version 3.1.2 the 'More compatible' setting in the CPU box is not on when you first start Amiberry. If I change the Amiga model in quickstart to something other than A500 and then back to A500 the 'More compatible' is set to on again. I'd always amused that Amiberry started with default A500 settings.

**Comment by midwan** [comment]
@Lex15 
Looks like you're right: the More compatible option was not always enabled when it should.

I've fixed that area and will push a new commit shortly.

**Comment by midwan** [comment]
This should be fixed with d7160fcbbe92fa4dcb0a1d6312af47bbfa8d2eb6 now. 
Please let me know if you still have any issues with it.

**Comment by Lex15** [comment]
A variation of this bug is back.  When Amiberry starts the default A500 quickstart is not loaded.  ECS is loaded not OCS.

**Comment by midwan** [comment]
@Lex15 Looks like you're right, thanks for noticing.
Let's handle this on a separate issue however - I'll open a new one.
