### ISSUE TITLE
Black screen when switching from RTG

### ISSUE THREAD

**Issue by DesertBlizzard** [midwan/amiberry#662]
Fully up-to-date Amibian 1.5ee and Amiberry 3.2beta, 2020/07/08 (and 07).  Amibian configured to boot directly to Amiberry, Amiberry configured for autostart into a tweaked-for-UAE version of Coffin56.

boot/config.txt HDMI mode
hdmi_group=2
hdmi_mode=07
hdmi_cvt=1280 1024 50 4

**To Reproduce**

- Power on system, get Amibian splash screen.
- Screen goes black as Amiberry loads.
- Amiberry pointer appears.
- WB appears.  Have both Linux and Amiga cursors on screen.  Out of sync since WB is set to 1024x768
- Press F12 to go into Amiberry GUI.
- Press F12 to return to WB.  Screen is black.  Continue to toggle, same result.
- Press F12 to go to Amiberry GUI
- Switch to Display option and change Screen Mode to any other mode.
- Press Resume or F12 and WB reappears.
- Press F12 again to go to Amiberry GUI and then once more to go back to WB, Black screen
- Repeat changing Screen Mode to any other option and WB reappears.
- Eventually Amiberry will crash either to the CLI, or simply lock up.

The black screen sometimes will occur when switching from an RTG mode to AGA.  Repeating the process above to change screen modes will restore AGA black screen, or if returning from an AGA mode (end of demo for instance) will return RTG screen.

**Comment by midwan** [comment]
@DesertBlizzard 
Are you using Fullscreen mode in Display?
That will switch the actual resolution on the monitor as well, but if your monitor doesn't support it, you might end up with an out-of-sync problem.
You can use Full-window instead, which will scale the image to the native resolution you currently have on the desktop. This is how it used to work by default before, when you asked for "fullscreen".

**Comment by DesertBlizzard** [comment]
None of these options have any effect on what the Pi does.  This might be because I am not using Amiberry from a DE, rather the system is launching Amiberry from rc.local.

**Comment by DesertBlizzard** [comment]
![Uploading 87078927...]()

**Comment by DesertBlizzard** [comment]
In getting you that screenshot, I pressed F12 after taking it and Amiberry locked up. No pointer or keyboard control. This was after starting up from a powered off state. Argon scripts still work since I can shut down gracefully with the Argon case power button.

**Comment by DesertBlizzard** [comment]
I will try setting WB to 1280x1024 to see if it behaves any differently.  FWIW, this was not a problem before, I think, the 2020/07/07 build.

**Comment by midwan** [comment]
But which Display option does your config start with?
Full screen or Full window?

**Comment by DesertBlizzard** [comment]
![20200709_190246437_iOS](https://user-images.githubusercontent.com/45675403/87087241-9fc02f80-c1e7-11ea-9d50-dfa4e36079d1.jpg)
This is how I have it configured.

**Comment by midwan** [comment]
Change that to full-window, save the config, then restart the emulator. 
Let me know if that changed anything?

**Comment by DesertBlizzard** [comment]
I still get the Linux cursor over the top of the Amiga cursor, but because the resolutions match they are bound together.

Once I press F12 I am presented with the Amiberry GUI, however if I immediately press F12 again without doing anything I am returned to a black screen.  Pressing F12 once again takes me back to the GUI. Pressing F12 over and over will always result in a black screen.

Now, If I change the screen mode from Full-Windowed (I picked fullscreen, but Windowed has the same effect) and press F12 not only am I returned to a visible WB, but the Linux cursor is now gone.

**Comment by midwan** [comment]
oh wait, you said Amibian...
Are you running the Dispmanx version of the emulator then? In that case, the display options have no effect, since Dispmanx is full-window always and ignores those options (I should update the gui to disable the dropdown in that scenario actually).

The cursor problem is a separate thing, which will be fixed (probably tonight). I was more interested in the black screen you mentioned, as that shouldn't be happening.
Can you confirm which is the last version that works for you, so we can trace this faster?

**Comment by DesertBlizzard** [comment]
Yes  Dispmanx indeed.  I have been compiling a lot lately.  I think whatever the code base was at prior to the date I mentioned above, 2020/07/07, but unfortunately I did not write that down.  One of my fatal flaws.

**Comment by midwan** [comment]
The "mouse cursor did not get grabbed on startup" bug is now fixed, with d525536

**Comment by DesertBlizzard** [comment]
I can confirm this fix.  This did not resolve the black screen problem, as I suspect you know.  I'm currently listening to the music of a demo I cannot see.  Interestingly, I cannot get the screen to reappear in the same manner I can with RTG by switching Screen Modes.  The demo, in case you are wondering, is Planet Hively.

**Comment by midwan** [comment]
The black screen bug should now be fixed also, with a9166eb8b83ec9ba83c6de42f4e7e4b3e83cfe5f
