### ISSUE TITLE
SDL2 | Keyboard input "spills" to the console

### ISSUE THREAD

**Issue by midwan** [midwan/amiberry#71]
This seems to be an issue with other SDL2 apps as well (might be an SDL2 bug?).
Keyboard input during emulation "spills" back to the console/system. Even if the GRAB_KEYBOARD Hint is enabled, it doesn't seem to work.

Keyboard input needs to be grabbed within the emulation session only.

**Comment by midwan** [comment]
Reported to SDL2's Bugzilla system: https://bugzilla.libsdl.org/show_bug.cgi?id=3611

**Comment by midwan** [comment]
Update: this only seems to happen if:

1. SDL2 was compiled from source to support opening screens directly from the console (i.e. no X11 requirement) 
2. OpenGL was disabled while compiling SDL2, because it has higher priority than OpenGLES2 (sigh) and leaving it enabled does not allow for point 1 above.

If instead we use OpenGL (enabled in raspi-config) and SDL2 compiled with opengl enabled, then launch an SDL2 app from X11, the problem does not occur.

This seems like a bug in SDL2 even more then.

**Comment by midwan** [comment]
Interesting find: In RetroPie 4.2, SDL2 is deployed as pre-compiled binaries.
Using that environment, the bug above does not occur.

Tried using the same pre-compiled SDL2 binaries on a fresh Raspbian installation, but there was no difference there (still got the problem), so it's not in the binaries themselves.

It looks like something else in the system configuration might be enabling this behavior, something that is in RetroPie but not in a stock Raspbian system.

**Comment by midwan** [comment]
Tested using the RetroPie approach and it seems to solve the problem.

The steps are:
1) git clone https://github.com/RetroPie/RetroPie-Setup
2) cd RetroPie-Setup
3) sudo ./retropie_packages.sh sdl2

This installs SDL2, so we still need SDL2_ttf and SDL2_image which should be installed from source as usual. After this is installed, running the emulator does not show the problem anymore.

It would be great to know what exactly fixes/changes this behavior, but at least we have a solution now.

**Comment by midwan** [comment]
For future reference, this is fixed with a patch on SDL sources: https://github.com/RetroPie/SDL-mirror/commit/294906558e67f7046b01bb2dc13da6c59a27db44

**Comment by windale** [comment]
I built using your latest instructions (use RetroPie SDL2) but I am still getting stuff spill to the console. Would this be because I previously had used your old method of installing SDL 2 ?

**Comment by midwan** [comment]
@windale 
Probably yes. Please try removing SDL2 first (run `sudo make uninstall` from within the build directory of SDL2), then install it using the instructions in the README.
