### ISSUE TITLE
Only V3.3 on RetroPie

### ISSUE THREAD

**Issue by Retro1968** [midwan/amiberry#807]
In the meantime you can only install amiberry V3.3 as source / binaries via the RetroPie setup. Tried it with RetroPie 4.7.11 and 4.7.12.

**Comment by midwan** [comment]
Yes, I am aware. But that is a RetroPie decision really.

I noticed a problem with RPI3s running Retropie, where the latest version shows a black screen when switching from the GUI to the emulation screen - perhaps that's one reason they've held back the update? It doesn't happen with RPI4s, and I'm looking for a solution to that in the meantime.

**Comment by joolswills** [comment]
This would be better brought up on the RetroPie forum.

There were some issues reported with v4.1.2 on the RetroPie forum that had been fixed in dev at the time I think so we rolled back to v3.3 to wait for the changes to reach master.

This was the thread

https://retropie.org.uk/forum/topic/30213/amiberry-4-0-released

**Comment by midwan** [comment]
@joolswills 
Indeed, some changes in the custom chipset made it in the v4.x release when they were not 100% finished yet. I'm syncing from WinUAE as soon as Toni makes any changes there, and I'll wait until he's finished with them before I merge them back to a new release.

Meanwhile, I just found out that on RPI3s specifically, v4.x releases have a "black screen" problem (if the GUI opens once, you cannot see the emulation screen anymore, it's always black), so I'm working on that.

For now, stick to v3.3 until the above problem is fixed at least, or until the custom chipset changes are done (that may take a while however, it depends on Toni's schedule).

**Comment by midwan** [comment]
I've now fixed the "black screen" bug in RPI3 platforms, so that's out of the way at least.

**Comment by HoraceAndTheSpider** [comment]
I still have some issues with the latest version running on Pi 3 on RetroPie though.

Identical setup on Pi 3 and Pi 4 and the -autoload function doesnt work on the 3. (it boots into kick 1.3 and the amiberrry.log shows it isnt even rying, but the amiberry.sh is operating correctly.)  

Also if i load a config manual after this (from the config panel) and hit 'reset' the emulator begins flickering screen and hangs.

**Comment by HoraceAndTheSpider** [comment]
Update: the `amiberry.sh` on the PI3 was out of date, and the syntax of --autoload needed updating.

The 'flicker screen' problem still happens though

**Comment by Retro1968** [comment]
> 
> 
> This would be better brought up on the RetroPie forum.
> 
> There were some issues reported with v4.1.2 on the RetroPie forum that had been fixed in dev at the time I think so we rolled back to v3.3 to wait for the changes to reach master.
> 
> This was the thread
> 
> https://retropie.org.uk/forum/topic/30213/amiberry-4-0-released

Is there a workaround for those RetroPie users who prefer to use the latest version of amiberry instead of version 3.3? So the question would be which file should be changed under RetroPie and how.

**Comment by midwan** [comment]
@Retro1968 
I usually just drop out to the console (`F4`), then grab the sources and compile them myself (instructions are in the Readme of this project). After that, I copy the binary in the expected location (`/opt/retropie/emulators/amiberry`) - you might want to keep a backup of the original 3.3 version there, before you do that.

**Comment by midwan** [comment]
@joolswills 
What is the status on this please?
I'm getting 4.2 ready for release soon(ish), so you might want to plan accordingly :)

**Comment by Retro1968** [comment]
> @Retro1968 I usually just drop out to the console (`F4`), then grab the sources and compile them myself (instructions are in the Readme of this project). After that, I copy the binary in the expected location (`/opt/retropie/emulators/amiberry`) - you might want to keep a backup of the original 3.3 version there, before you do that.

Since a while i edited the file "amiberry.sh" in the folder "/home/pi/RetroPie-Setup/scriptmodules/emulators", like this

rp_module_repo="git https://github.com/midwan/amiberry master"

so i got everytime the newest sourcecode when using the RetroPie-Setup.

Yesterday I wanted to update to the new amiberry 4.2.0 version via the RetroPie setup via source code. While the new code was downloaded without any problems, the compilation process broke off with an error message. This was to be expected since Midwan changed the compile options. Midwan can you take a look at my amiberry.sh and change it so that it compiles correctly again? 

Kind Regards
Retro1968

[amiberry.zip](https://github.com/midwan/amiberry/files/7925261/amiberry.zip)

**Comment by midwan** [comment]
@Retro1968 
Which platform are you using?
I've created a wiki page with all the available platforms here: https://github.com/midwan/amiberry/wiki/Available-Platforms

**Comment by midwan** [comment]
I've also updated the wiki page about upgrading, with instructions for people wanting to get the latest Amiberry version running on Retropie: https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version

@joolswills any progress on offering newer versions through RetroPie-Setup?

**Comment by Retro1968** [comment]
> I've also updated the wiki page about upgrading, with instructions for people wanting to get the latest Amiberry version running on Retropie: https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version
> 
> @joolswills any progress on offering newer versions through RetroPie-Setup?

Danke für die schöne Anleitung. Ich glaube Du hast noch vergessen, der Datei amiberry die Rechte 755 zu geben und nach "/opt/retropie/emulators/amiberry/" zu kopieren. :-)

**Comment by Retro1968** [comment]
> I've also updated the wiki page about upgrading, with instructions for people wanting to get the latest Amiberry version running on Retropie: https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version
> 
> @joolswills any progress on offering newer versions through RetroPie-Setup?

Thanks for the nice guide. I think you forgot to give the amiberry file permissions 755 and copy it to "/opt/retropie/emulators/amiberry/". :-)

**Comment by midwan** [comment]
> > I've also updated the wiki page about upgrading, with instructions for people wanting to get the latest Amiberry version running on Retropie: https://github.com/midwan/amiberry/wiki/Upgrading-to-the-latest-version
> > @joolswills any progress on offering newer versions through RetroPie-Setup?
> 
> Thanks for the nice guide. I think you forgot to give the amiberry file permissions 755 and copy it to "/opt/retropie/emulators/amiberry/". :-)

Indeed, thanks for pointing that out! Fixed.

**Comment by nemo93** [comment]
Update to 5.x is coming to Retropie. Check that [PR](https://github.com/RetroPie/RetroPie-Setup/pull/3508). It should take a bit more time to smoothen the edge but it's there for good ;-)
