### ISSUE TITLE
SDL 2 | Segmentation fault when trying to use directories as harddisks

### ISSUE THREAD

**Issue by rabejens** [midwan/amiberry#92]
With the latest state of the SDL2 version built on the Pi3, I get a segmentation fault when I want to use directories as hard drives. The segfault happens as soon as the virtual HDD is accessed.

Steps to reproduce:

- Start with a basic A500 or A1200 configuration
- Add an empty directory as a harddisk and make it bootable
- Start the emulation

Result: You will be dropped out of the emulation with a segfault.

If you make the hard disk non-bootable and start from a Workbench disk, the segfault happens as soon as `loadwb` is executed, i.e., when it first accesses the harddisk.

**Followup:** This also happens when I try to create a HDF file. When I hit "Create HDF" and enter the details and accept the entries, when it starts to create the file, it segfaults.

**Followup 2:** The hardfile *DOES* get created, so when I restart Amiberry after the segfault and use the hardfile, it can be used.

**Comment by pawelomega** [comment]
processed: 1989048396
Segmentation fault
and when Segmentation fault then exit from Amiberry and access to keyboard in console is blocked.

This error persits when Amiberry start with attached Amiga hdf .

**Comment by rabejens** [comment]
Currently I only setup one HDF, I could install Workbench 3.1 with BetterWB on it and it works. But as soon as I add any directories, I get the segfault (and the keyboard stopping working, too)

**Comment by midwan** [comment]
Please get the latest changes and test again, after merging #85 this should be resolved

**Comment by pawelomega** [comment]
Latest build from source and problem persist. Crashing with added HDD DIRECTORY when booted workbench.

**Comment by midwan** [comment]
@pawelomega 
Thanks for reporting, I'll take a closer look later today when I'm back home
